copyright = "Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved."
spdx-license-identifier = "CC-BY-SA-4.0"

# Set your own baseURL if it's different
baseURL = "YOUR_BASEURL"
languageCode = "en-US"
defaultContentLanguage = "en"

title = "Messaging in the Cloud"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = false
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

enableEmoji = true

[params]
  description = "Messaging in the Cloud covers the patterns and best practices with messaging using services SQS, SNS, Amazon MQ, EventBridge"
  author = "Dragan Jovanovic"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true

[outputs]
  home = [ "HTML", "RSS", "JSON"]

[blackfriday]
  plainIDAnchors = true
  hrefTargetBlank = true

[Languages]
[Languages.en]
  title = "Messaging in the Cloud"
  weight = 1
  languageName = "English"
